### ISSUE TITLE
Concatenation of masks

### ISSUE THREAD

**Issue by alekstar79** [Tamersoul/magic-wand-js#11]
Please tell me if it is possible to concatenate masks? That is I mean the standard behavior of the magic wand in image editors. When the shift key is pressed and another point is specified - the newly calculated mask, adds up to the already overlaid mask. Or can you tell me an approximate algorithm for concatenation of masks.

**Comment by Tamersoul** [comment]
see the method **concatMasks** in updated live example
http://jsfiddle.net/Tamersoul/dr7Dw/

**Comment by alekstar79** [comment]
Yes, thank you. I have already implemented something similar. Only I did it in the floodfill methods. To do this I had to change the code of your lib, which is not good but everything also worked. A separate function is better. I think you should consider adding it directly to the library's methods. Thank you again.
