### ISSUE TITLE
floodfill: 1px at all image borders was missing

### ISSUE THREAD

**Issue by luxlux** [Tamersoul/magic-wand-js#5]
The mask created by floodfill is missing 1 pixel at all inner image borders. 
It is noticeable if NO border blur will be used. 

I have changed this in my fork:
https://github.com/luxlux/magic-wand-js/blob/master/js/magic-wand.js
In this version also the pixels at the image border will be masked.

**Comment by Tamersoul** [comment]
Done!
Added parameter **includeBorders** to **floodFill**
